### ISSUE TITLE
DE Compat

### ISSUE THREAD

**Issue by TerdyTheTerd** [TerdyTheTerd/Techguns2#5]
Creating this to hopefully get some feedback regarding changes made for other mods custom armor compatibility, specifically DE. Please note that the changes made will break turrets and the armors from TG (TG armors will still work, but some of their custom armor attributes wont apply properly). The changes also include a few additional things such as headshot bonus, direct hit bonus, piercing ammo (not finished), and will include various console messages. Once final changes are made after testing feedback I can isolate just the compat changes and remove the others for players who only want the compat fixes. You will need to checkout the DE-Compat branch and build it. @Kodiax1, @AndreaS992, @Libright1558

**Comment by rperraudeau** [comment]
Hey!
Thank you for attempting a compatibility with Draconic Evolution.
I'm going to try it today, but I'm nothing of a java developper, so I'll do my best, even if I'm not used to java environment.

I will send you my feedback as soon as possible.

If I understood, I have to build it with Gradle ?
Something else to know ?

Thanks !

**Comment by rperraudeau** [comment]
Ok !
I just got it working, so, first impression: it looks like it is working like a charm. Most of mobs I met couldn't bypass my Draconic armor shield anymore. So, exactly what was expected.

It looks like your fork was missing some of the last updates of the original mod, but I just removed these blocks from my world. Nothing important.

I'll keep trying it these days, and I'll give more feedback to you this week-end.

Again, thank you.

Oh! And, here is how I proceeded to get it working, if someone else is interested:

> 1) download and extract the zip archive somewhere on your computer.
> 2) install Gradle ("apt install gradle" on recent debian-based system, or report to the Gradle doc in other case)
> 3) open a console and go to the main directory of the mod
> 4) type "gradle build"
> 5) Copy the techguns-1.12.2-2.0.2.0.jar file (found in build/libs) in your minecraft mods directory (not the -source.jar)
> 6) Run minecraft & Enjoy

Finally, for information purpose, I tried with "gradle jar" instead of "gradle build" but it seems buggy, and I get an error while launching minecraft, something like "CreativeTabBackgroundName error" or something, I just removed the "build" directory and ran the other command)

**Comment by TerdyTheTerd** [comment]
I have not kept up with the mods after my initial attempt at making a compatibility patch, as I never received any initial feedback from those that expressed initial interest. As such its entirely possible that these changes no longer work with newer versions, or that the respective authors of those mods have already implemented their own fixes.

On a side note, the changes posted on this fork are not complete. Some custom armors from TG and their turret system do not work with these changes. If you have other mods with similar functionality, I would suggest using those and disabling these features from this mod.

**Comment by rperraudeau** [comment]
Hello !
I Actually never use TechGun turrets, i was already using Modular Turret mod instead, so no problem for me.
Well i tried some different things, and it looks like it's working well with both Wyvern armor, and Draconic armor. The only trouble I found wasn't with Draconic Evolution itself, but with an addon, Draconic Additions: I just upgraded my Draconic Armor to a Chaos Armor, and Shield doesn't seem to work in that case.
Only thing i found ATM :+1:

**Comment by TerdyTheTerd** [comment]
I just did a very quick glance over Draconic Additions source code, I don't see them using any special or custom event handlers for armors or damage or anything like that. Are the shields from that just not working when being shot with TG guns, or are the shields just not working in general (the latter pointing to an issue elsewhere). Just out of curiosity are you trying these changes out for single player or were you looking for a solution for a private/public modpack/server?

P.S. - don't take this as a sign that I will be actively working on this, didn't want to get any hopes up I just had a few minutes to spare :p

**Comment by rperraudeau** [comment]
Don't worry take your time, it's nice of you to take a look, i can't ask more !

The shield is working well in general, just doesn't work with TG guns.

At the moment I only try this in singleplayer, but I plan to, probably, create a modpack around Stargate. Not sure if I will or when i will, as I have already a lot of "work" to do with building all the lore planets. So it's for myself ATM, I just will be happy to release it if i can have something stable, add some stages to limit technologies, and restrict some OP items. And I actually find that DE/DA armors fit well with Goa'uld shield for the late game. But i still don't know if it will be single or multiplayer based.

**Comment by TerdyTheTerd** [comment]
Off topic here, but the GameStages mod series, paired with CraftTweaker, offer great flexibility when it comes to gating/progression. I usually see some questing mod (FTB Quest, BetterQuesting, Triumph+BetterAdvancements) used as the sorta interface or guide.

I'll leave this ticket open as I recently started working on a modpack as well, which may need to include TG, so I might be forced to finish what I started after all.

**Comment by Spiderwalker987** [comment]
> Ok !
> I just got it working, so, first impression: it looks like it is working like a charm. Most of mobs I met couldn't bypass my Draconic armor shield anymore. So, exactly what was expected.
> 
> It looks like your fork was missing some of the last updates of the original mod, but I just removed these blocks from my world. Nothing important.
> 
> I'll keep trying it these days, and I'll give more feedback to you this week-end.
> 
> Again, thank you.
> 
> Oh! And, here is how I proceeded to get it working, if someone else is interested:
> 
> > 1. download and extract the zip archive somewhere on your computer.
> > 2. install Gradle ("apt install gradle" on recent debian-based system, or report to the Gradle doc in other case)
> > 3. open a console and go to the main directory of the mod
> > 4. type "gradle build"
> > 5. Copy the techguns-1.12.2-2.0.2.0.jar file (found in build/libs) in your minecraft mods directory (not the -source.jar)
> > 6. Run minecraft & Enjoy
> 
> Finally, for information purpose, I tried with "gradle jar" instead of "gradle build" but it seems buggy, and I get an error while launching minecraft, something like "CreativeTabBackgroundName error" or something, I just removed the "build" directory and ran the other command)

Hi, I'm quite new to these sorts of things and am wondering how exactly this is done. More specifically, could each step be explained a little bit further. I have downloaded Gradle and have installed it successfully. I am encountering the TechGuns/DE issue and would like to resolve it. I am using the ATLauncher if that changes anything. I find it easier to use in handling mods and am running a modified Resonant Rise pack that has certain mods added/removed.
Any reply is greatly appreciated!

**Comment by Spiderwalker987** [comment]
So I've actually gotten Gradle to work very well and it does build inside the main directory of the compat patch, but I do not see a build folder after I do the 'gradle build' command. Am I missing something?

**Comment by lgireli** [comment]
i have recently built this but when i get hit by anything, my game lags horribly, what could be the issue, it happens in single player and in multiplayer aswell

**Comment by TerdyTheTerd** [comment]
@lukas0cv No idea, this fork is nearly two years old and I haven't played or looked at any mods in over a year and a half. I believe this issue was addressed elsewhere on the main repo or a better patch was available elsewhere. Sorry I don't have more info, I'll close this out now as I won't be returning to make any updates to the code.
